### ISSUE TITLE
Can't get out of the first room?

### ISSUE THREAD

**Issue by hemingtv** [AngusBethke/rs_dyinglight2_projects#1]
hi, i just downloaded the intersection map, im not sure if i'm just stupid and im doing something wrong but when i go to pick the lock on the door the lockpick just becomes static and doesn't move. it'll make sounds when i press the normal keys to lockpick but nothing happens. to the right of the door is a grey box with a knife next to it. I'm not sure if i'm missing something and this is just an escape the room type of puzzle. I restarted the map, then uninstalled and reinstalled the map and even restarted the game. 

here is a [link](https://youtu.be/9-AI2yhBZCs) to a video showing what's happening

**Comment by AngusBethke** [comment]
Hi there, thanks for logging an issue.

I've watched the video and that does seem strange.

Just confirming: 
- Are you launching from the DL2 custom maps menu in-game?

I haven't encountered that issue before, so I will look into it. 

Will feedback as soon as I am able.

**Comment by hemingtv** [comment]
Thanks for the reply, yeah I downloaded and launched the map from the in game community maps thing.

**Comment by AngusBethke** [comment]
Hey again, the problem should now be patched with 0.4.0. Just to note, there are intermittent crashing issues with most of the community maps when launching from the DL2 menu. "The Intersection" ran fine in my test run, buuuuut it's possible you'll run into the issue. Let me know if you bump into the issue and I will forward to Techland.

PS: Sorry for the delay, was away on Honeymoon.

**Comment by hemingtv** [comment]
Hey! Sounds good thanks for your work homie, I’ll fire it up later today and see if it works. If for whatever reason it doesn’t I’ll try getting it from the mod website. No worries about the time it took, congratulations on your marriage!
