### ISSUE TITLE
Cant access on PC (I know how to fix)

### ISSUE THREAD

**Issue by gregsmeffley** [AngusBethke/rs_dyinglight2_projects#2]
When I say I know how to fix it it is more like a very educated guess, this map doesn't show up in "community maps "(I don't think it does this on any platform) I think the issue is because it is not listed what platform it works on, on the mod.io website you can see all the maps perfectly, but when in "community maps" in dl2 only a few of them show up, I think its because of the filter on the left side when on the website (which I'm assuming got added recently and not many of the map developers realise its there), when I put on the "windows" filter (I'm on pc) the few maps that show up in "community maps" then only show in mod.io, so I think you have to have the map tagged with what platforms you want it on for it to show up on, or else it doesn't appear. 
![image](https://github.com/AngusBethke/rs_dyinglight2_projects/assets/152783571/95ce965b-fae0-4ab8-ae72-53589dbc7b9c)

**Comment by AngusBethke** [comment]
Hey there, 

We don't control those tags as creators unfortunately, Techland has a review process that eventually adds those tags when they're happy for the maps to transition to the relevant platforms. "What Remains of Oldtown" and a few other maps on Mod.io are still pending review from Techland.

**Comment by gregsmeffley** [comment]
well thats a shame, i hope it gets added soon since i dont think anyone can
access half of the maps

**Comment by AngusBethke** [comment]
It's been a little while... but "What Remains of Oldtown" has transformed into "The Vault" - it is fortuantely available on all platforms as well, I will close this issue.
